name: kelp
channels:
  - conda-forge
  - anaconda
  - pyviz
dependencies:
  - pymc3
  - llvm
  - clang-11
  - exoplanet
  - geoviews
  - nbsite
  - nbconvert==5.6.1
  - python-chromedriver-binary
  - firefox
  - geckodriver
  - selenium
